---
name: NPP
services:
  server:
    container_name: npp_server
    build:
      context: ./TCP/server_dir
    expose:
      - 4242
    networks:
      - npp
    command:
      - ./server
      - Hello from Server!
    stdin_open: true
    tty: true
  client:
    container_name: npp_client
    build:
      context: ./TCP/client_dir
    depends_on:
      - server
    expose:
      - 4242
    networks:
      - npp
    command:
      - ./client
      - server
    stdin_open: true
    tty: true
  chatserver:
    container_name: npp_chatserver
    build:
      context: ./TCP/chatserver_dir
    expose:
      - 4242
    networks:
      - npp
    command:
      - ./chatserver
    stdin_open: true
    tty: true
  chatclient:
    container_name: npp_chatclient
    build:
      context: ./TCP/chatclient_dir
    depends_on:
      - chatserver
    expose:
      - 4242
    networks:
      - npp
    command:
      - ./chatclient
      - chatserver
    stdin_open: true
    tty: true
  listener:
    container_name: npp_listener
    build:
      context: ./UDP/listener_dir
    expose:
      - 4242
    networks:
      - npp
    command:
      - ./listener
    stdin_open: true
    tty: true
  talker:
    container_name: npp_talker
    build:
      context: ./UDP/talker_dir
    depends_on:
      - listener
    expose:
      - 4242
    networks:
      - npp
    command:
      - ./talker
      - listener
      - Hello from Talker!
    stdin_open: true
    tty: true

networks:
  npp:
    driver: bridge
