name: NPP

services:
  server:
    build:
      context: ./TCP/server_dir
      dockerfile: Dockerfile
    container_name: npp_server
    networks:
      - npp
    command: ["./server"]

  client:
    build:
      context: ./TCP/client_dir
      dockerfile: Dockerfile
    container_name: npp_client
    networks:
      - npp
    depends_on:
      - server
    command: ["./client", "server"]

  listener:
    build:
      context: ./UDP/listener_dir
      dockerfile: Dockerfile
    container_name: npp_listener
    networks:
      - npp
    command: ["./listener"]

  talker:
    build:
      context: ./UDP/talker_dir
      dockerfile: Dockerfile
    container_name: npp_talker
    networks:
      - npp
    depends_on:
      - listener
    command: ["./talker", "listener"]

networks:
  npp:
    driver: bridge
